# Generated by Django 5.0 on 2024-02-01 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=100, verbose_name='page_title')),
                ('page_discription', models.CharField(max_length=500, verbose_name='page_discription')),
                ('page_content', models.CharField(max_length=1000, verbose_name='Content')),
                ('page_url', models.CharField(default='', max_length=100, verbose_name='Slug')),
                ('published_date', models.IntegerField(default=datetime.datetime(2024, 2, 1, 20, 16, 52, 462471))),
            ],
        ),
    ]
