# Generated by Django 5.0 on 2024-02-06 01:30

import datetime
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='page_title')),
                ('discription', models.CharField(blank=True, max_length=500, verbose_name='page_discription')),
                ('discriptive_image', models.ImageField(blank=True, upload_to='img/')),
                ('h2', models.CharField(blank=True, max_length=100, verbose_name='heading 2')),
                ('content', tinymce.models.HTMLField(blank=True)),
                ('h3', models.CharField(blank=True, max_length=100, verbose_name='heading 3')),
                ('h4', models.CharField(blank=True, max_length=100, verbose_name='heading 4')),
                ('second_content', tinymce.models.HTMLField(blank=True)),
                ('image', models.ImageField(default='', upload_to='img/')),
                ('url', models.CharField(max_length=100, verbose_name='Slug')),
                ('published_date', models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 30, 39, 455894, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
