# Generated by Django 5.0 on 2024-02-05 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 9, 6, 35, 833364, tzinfo=datetime.timezone.utc)),
        ),
    ]
