# Generated by Django 5.0 on 2024-02-01 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.IntegerField(default=datetime.datetime(2024, 2, 1, 20, 17, 25, 366566)),
        ),
    ]
