# Generated by Django 5.0 on 2024-02-01 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_page_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 20, 29, 37, 122968)),
        ),
    ]
