# Generated by Django 5.0 on 2024-02-06 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_person_alter_page_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=100, verbose_name='card text')),
                ('title', models.CharField(max_length=100, verbose_name='card title')),
                ('discription', models.CharField(max_length=100, verbose_name='Discription[ short ]')),
                ('working_day_from', models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Thursday'), ('W', 'Wednesday'), ('F', 'Friday'), ('S', 'Sunday')], max_length=10)),
                ('working_day_to', models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Thursday'), ('W', 'Wednesday'), ('F', 'Friday'), ('S', 'Sunday')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 2, 29, 53, 419647, tzinfo=datetime.timezone.utc)),
        ),
    ]
