# Generated by Django 5.0 on 2024-02-06 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_topcard_delete_person_alter_page_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcard',
            name='working_hour_from',
            field=models.CharField(blank=True, choices=[('A', '6:00 PM')], max_length=10),
        ),
        migrations.AddField(
            model_name='topcard',
            name='working_hour_to',
            field=models.CharField(blank=True, choices=[('A', '6:00 PM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 2, 37, 31, 17802, tzinfo=datetime.timezone.utc)),
        ),
    ]
