# Generated by Django 5.0 on 2024-02-02 13:29

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_page_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
