# Generated by Django 5.0 on 2024-02-06 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_topcard_working_hour_from_topcard_working_hour_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 3, 40, 18, 366228, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='topcard',
            name='discription',
            field=models.CharField(max_length=100, verbose_name='Discription [short]'),
        ),
        migrations.AlterField(
            model_name='topcard',
            name='working_day_from',
            field=models.CharField(blank=True, choices=[('A', 'Monday'), ('B', 'Tuesday'), ('C', 'Wednesday'), ('D', 'Thursday'), ('E', 'Friday'), ('F', 'Saturday'), ('G', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='topcard',
            name='working_day_to',
            field=models.CharField(blank=True, choices=[('A', 'Monday'), ('B', 'Tuesday'), ('C', 'Wednesday'), ('D', 'Thursday'), ('E', 'Friday'), ('F', 'Saturday'), ('G', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='topcard',
            name='working_hour_from',
            field=models.CharField(blank=True, choices=[('9:00 AM', 'A'), ('B', '10:00 AM'), ('C', '11:00 AM'), ('D', '12:00 AM'), ('E', '1:00 PM'), ('F', '2:00 PM'), ('G', '3:00 PM'), ('H', '4:00 PM'), ('I', '5:00 PM'), ('J', '6:00 PM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='topcard',
            name='working_hour_to',
            field=models.CharField(blank=True, choices=[('9:00 AM', 'A'), ('B', '10:00 AM'), ('C', '11:00 AM'), ('D', '12:00 AM'), ('E', '1:00 PM'), ('F', '2:00 PM'), ('G', '3:00 PM'), ('H', '4:00 PM'), ('I', '5:00 PM'), ('J', '6:00 PM')], max_length=10),
        ),
    ]
