# Generated by Django 5.0 on 2024-02-06 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_homepagecontent_alter_page_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='batch_3_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='batch 3 heading'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='batch_3_price',
            field=models.CharField(blank=True, max_length=100, verbose_name='batch 3 price'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='batch_1_content',
            field=models.CharField(blank=True, max_length=1000, verbose_name='batch 1 content'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='batch_1_heading',
            field=models.CharField(blank=True, max_length=100, verbose_name='batch 1 heading'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='batch_1_price',
            field=models.CharField(blank=True, max_length=100, verbose_name='batch 1 price'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='batch_3_content',
            field=models.CharField(blank=True, max_length=1000, verbose_name='batch 3 content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 14, 10, 54, 653830, tzinfo=datetime.timezone.utc)),
        ),
    ]
