# Generated by Django 5.0 on 2024-02-06 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_homepagecontent_batch_3_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 14, 22, 46, 229211, tzinfo=datetime.timezone.utc)),
        ),
    ]
