# Generated by Django 5.0 on 2024-02-06 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_page_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='help_box_1',
            field=models.CharField(default='', max_length=400, verbose_name='Help Box 1'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='help_box_2',
            field=models.CharField(default='', max_length=400, verbose_name='Help Box 2'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 19, 22, 44, 197444, tzinfo=datetime.timezone.utc)),
        ),
    ]
