# Generated by Django 5.0 on 2024-02-06 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_homepagecontent_help_box_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='help_box_1_h5',
            field=models.CharField(default='', max_length=100, verbose_name='Help Box 1 Heading'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='help_box_2_h5',
            field=models.CharField(default='', max_length=100, verbose_name='Help Box 2 Heading'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='help_box_3',
            field=models.CharField(default='', max_length=400, verbose_name='Help Box 3'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='help_box_3_h5',
            field=models.CharField(default='', max_length=100, verbose_name='Help Box 3 Heading'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 19, 29, 46, 944440, tzinfo=datetime.timezone.utc)),
        ),
    ]
