# Generated by Django 5.0 on 2024-02-06 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_homepagecontent_help_box_1_h5_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopCard',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='dctor_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Doctors Name'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_day_from',
            field=models.CharField(blank=True, choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thurs'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_day_to',
            field=models.CharField(blank=True, choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thurs'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_hour_from',
            field=models.CharField(blank=True, choices=[('9:00 AM', '9'), ('10:00 AM', '10'), ('11:00 AM', '11'), ('12:00 AM', '12'), ('1:00 PM', '1'), ('2:00 PM', '2'), ('3:00 PM', '3'), ('4:00 PM', '4'), ('5:00 PM', '5'), ('6:00 PM', '6')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_hour_to',
            field=models.CharField(blank=True, choices=[('9:00 AM', '9'), ('10:00 AM', '10'), ('11:00 AM', '11'), ('12:00 AM', '12'), ('1:00 PM', '1'), ('2:00 PM', '2'), ('3:00 PM', '3'), ('4:00 PM', '4'), ('5:00 PM', '5'), ('6:00 PM', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='discription',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discription [short]'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='card title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 22, 46, 46, 897381, tzinfo=datetime.timezone.utc)),
        ),
    ]
