# Generated by Django 5.0 on 2024-02-07 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_remove_appointment_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='batch_2_content',
            field=models.CharField(blank=True, max_length=1000, verbose_name='batch 2 content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 0, 11, 16, 671959, tzinfo=datetime.timezone.utc)),
        ),
    ]
