# Generated by Django 5.0 on 2024-02-08 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_alter_page_content_alter_page_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 6, 19, 56, 825302, tzinfo=datetime.timezone.utc)),
        ),
    ]
