# Generated by Django 5.0 on 2024-02-09 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_alter_page_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='dctor_name',
            new_name='doctor_name_1',
        ),
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='working_day_from',
            new_name='working_day_from_1',
        ),
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='working_day_to',
            new_name='working_day_from_2',
        ),
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='working_hour_from',
            new_name='working_hour_from_1',
        ),
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='working_hour_to',
            new_name='working_hour_from_2',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discription_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discription [short]'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discription_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discription [short]'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discription_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discription [short]'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='doctor_name_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Doctors Name'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='doctor_name_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Doctors Name'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='title_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='card title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='title_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='card title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='title_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='card title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_day_from_3',
            field=models.CharField(blank=True, choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thurs'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_day_to_1',
            field=models.CharField(blank=True, choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thurs'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_day_to_2',
            field=models.CharField(blank=True, choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thurs'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_day_to_3',
            field=models.CharField(blank=True, choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thurs'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_hour_from_3',
            field=models.CharField(blank=True, choices=[('9:00 AM', '9'), ('10:00 AM', '10'), ('11:00 AM', '11'), ('12:00 AM', '12'), ('1:00 PM', '1'), ('2:00 PM', '2'), ('3:00 PM', '3'), ('4:00 PM', '4'), ('5:00 PM', '5'), ('6:00 PM', '6')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_hour_to_1',
            field=models.CharField(blank=True, choices=[('9:00 AM', '9'), ('10:00 AM', '10'), ('11:00 AM', '11'), ('12:00 AM', '12'), ('1:00 PM', '1'), ('2:00 PM', '2'), ('3:00 PM', '3'), ('4:00 PM', '4'), ('5:00 PM', '5'), ('6:00 PM', '6')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_hour_to_2',
            field=models.CharField(blank=True, choices=[('9:00 AM', '9'), ('10:00 AM', '10'), ('11:00 AM', '11'), ('12:00 AM', '12'), ('1:00 PM', '1'), ('2:00 PM', '2'), ('3:00 PM', '3'), ('4:00 PM', '4'), ('5:00 PM', '5'), ('6:00 PM', '6')], max_length=10),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='working_hour_to_3',
            field=models.CharField(blank=True, choices=[('9:00 AM', '9'), ('10:00 AM', '10'), ('11:00 AM', '11'), ('12:00 AM', '12'), ('1:00 PM', '1'), ('2:00 PM', '2'), ('3:00 PM', '3'), ('4:00 PM', '4'), ('5:00 PM', '5'), ('6:00 PM', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='discription',
            field=models.CharField(blank=True, max_length=500, verbose_name='Site Discription'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Site Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.CharField(blank=True, max_length=500, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 15, 16, 16, 381017, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='second_content',
            field=models.CharField(blank=True, max_length=500, verbose_name='second content'),
        ),
    ]
