# Generated by Django 5.0 on 2024-02-11 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_rename_dctor_name_homepagecontent_doctor_name_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='google',
            field=models.CharField(blank=True, max_length=1000, verbose_name='google +'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1000, verbose_name='linkedin link'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='pinterest',
            field=models.CharField(blank=True, max_length=1000, verbose_name='pinterest link'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='twitter',
            field=models.CharField(blank=True, max_length=1000, verbose_name='twitter link'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 14, 2, 53, 127372, tzinfo=datetime.timezone.utc)),
        ),
    ]
