# Generated by Django 5.0 on 2024-02-11 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_homepagecontent_facebook_homepagecontent_google_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='heading_slider_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Heading Slider 1'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='heading_slider_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Heading Slider 2'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='heading_slider_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Heading Slider 3'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='text_slider_1',
            field=models.CharField(blank=True, max_length=500, verbose_name='text slider 1'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='text_slider_2',
            field=models.CharField(blank=True, max_length=500, verbose_name='text slider 2'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='text_slider_3',
            field=models.CharField(blank=True, max_length=500, verbose_name='text slider 3'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 14, 50, 21, 407796, tzinfo=datetime.timezone.utc)),
        ),
    ]
